---
title: "DAOY-SPHER_Seurat_EXPLORE1_50K"
author: "JJ"
date: "2023-01-26"
output: html_document
---

```{r graphical_output}
options(bitmapType='cairo-png') # this line of code needed BEFORE knitr code in chunk below
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = TRUE,   # prints the code (if FALSE then only code output is shown)
                      cache = TRUE,
                      fig.path = "./outputs50K/ONS76_SPHER/figures/")
```

```{r libraries}
suppressPackageStartupMessages({
library(Seurat)
library(glmGamPoi)
library(presto)
library(clustree)
library(tidyverse)
library(magrittr)
library(patchwork)
})
```

```{r}
# load the data from scratch
# load the DAOY-SPHER raw data (from "working_data" folder)
data_dir <- "./working_data/DAOY-SPHER/"
list.files(data_dir) # should show matrix.mtx.gz, features.tsv.gz, barcodes.tsv.gz
```

```{r}
# note these are .gz files which can be directly read. n = 761 cells (in dySpher.data)
dySpher.data <- ReadMtx(mtx = paste0(data_dir, "matrix.mtx.gz"),
                         features = paste0(data_dir, "features.tsv.gz"), 
                         cells = paste0(data_dir, "barcodes.tsv.gz"))
# create the seurat object, keep genes expressed in 10 or more cells
dySpher <- CreateSeuratObject(counts = dySpher.data,
                          min.cells = 10, min.genes=200,
                          project = "dySpher")

dim(dySpher) # 16,238 genes and 761 cells
```


```{r}
# identify mitochondrial genes
mito.genes <- grep(pattern = "^MT", x = rownames(x = dySpher), value = TRUE)
percent.mito <- 
  Matrix::colSums(dySpher[mito.genes, ])/Matrix::colSums(dySpher)

# add the mitochondrial gene percent to the metadata
dySpher <- 
  AddMetaData(object = dySpher, metadata = percent.mito, col.name = "percent.mito")

# remove mitochondrial genes 
dySpher <- dySpher[ ! grepl("^MT-", rownames(dySpher)), ]

dim(dySpher) # 16,225 genes and 761 cells
```

```{r}
# remove all cells with percent.mito > 10%
dySpher <- subset(dySpher, subset = percent.mito < 0.1)
dim(dySpher) # reduced to 16,225 genes and 649 cells
```

```{r}
# save the NON-normalised, NON-clustered cbo seurat object
saveRDS(dySpher, file = "./outputs50K/DAOY_SPHER/filt.MitoCellsGenes.RiboRetained.seurat.DAOYspher.rds")
```

```{r}
dySpher <- readRDS("outputs50K/DAOY_SPHER/filt.MitoCellsGenes.RiboRetained.seurat.DAOYspher.rds")
```

```{r}
# load cell cycle genes, calculate cell-cycle difference in advance of regressing out CC difference

# normalise object before running cell cycle scores as per Seurat github issue: https://github.com/satijalab/seurat/issues/1679
dySpher <- NormalizeData(dySpher)

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
# calculate CC difference
dySpher <- CellCycleScoring(dySpher,
                g2m.features = g2m.genes,
                s.features = s.genes)
dySpher$CC.difference <- dySpher$S.Score - dySpher$G2M.Score
```

```{r}
# this object is input for integration - already SCTransformed, CCdiff regressed, and RunPCA()
dySpher.input.integration <- SCTransform(dySpher, 
                   vars.to.regress = "CC.difference",
                   method = "glmGamPoi",
                   vst.flavor = "v2",
                   verbose = FALSE) %>% 
  RunPCA(npcs = 30, verbose = FALSE)
```

```{r}
# saved the SCTransformed object, CC difference regressed, PCA reduction, as input for integrated workflow
saveRDS(dySpher.input.integration, "./outputs50K/DAOY_SPHER/DAOYspher.inputIntegration.RiboRetained.SCTransformed.CCdiffRegressed.PCA.unclustered.rds")
```

```{r}
dySpher <- SCTransform(dySpher, vars.to.regress = "CC.difference", method = "glmGamPoi", verbose = FALSE) %>% 
  RunPCA(verbose = FALSE) %>% 
  RunUMAP(dims=1:30, verbose=FALSE) %>% 
  FindNeighbors(dims=1:30, verbose=FALSE) %>% 
  FindClusters(verbose=FALSE, resolution = 0.5)
```

```{r}
# save the clustered, SCTransformed object above
saveRDS(dySpher, file = "./outputs50K/DAOY_SPHER/DAOYspher.MitoCellsGenesFilt.RiboRetained.SCT.clustered.CCdiffRegressed.rds")
```

```{r}
# load the above object
dySpher <- readRDS("outputs50K/DAOY_SPHER/DAOYspher.MitoCellsGenesFilt.RiboRetained.SCT.clustered.CCdiffRegressed.rds")
```

```{r DimplotONS76monoUmapSCTransform, fig.height=6, fig.width=10}
DimPlot(dySpher, label = TRUE)
```

```{r}
# get the markers of each cluster
dySpher.POSmarkers <- FindAllMarkers(object = dySpher, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```

```{r}
# cluster 2 only is enriched for ribosome genes
dySpher.POSmarkers %>% 
  dplyr::group_by(cluster) %>% 
  slice_head(n = 30)
```

```{r}
# MEIS1 is expressed of these five
dySpher.POSmarkers %>%
  filter(gene %in% c("NEUROD1", "CNTN1", "CNTN2", "MEIS1", "DCX"))
```

```{r}
# save the positive markers of DAOY_SPHER
saveRDS(dySpher.POSmarkers, 
        file = "./outputs50K/DAOY_SPHER/POS.markers.DAOYspheroid.RiboRetained.SCT.clustered.rds")
```

```{r}
dySpher.POSmarkers <- readRDS("outputs50K/DAOY_SPHER/POS.markers.DAOYspheroid.RiboRetained.SCT.clustered.rds")
```

```{r}
table(Idents(dySpher))
```

As with ONS76-spheroid cluster 4, the DAOY-spheroid cluster 4 expresses proliferation markers
```{r HeatmapDaoySpherTop10markers4clustersRes0.5, fig.height=8, fig.width=10}
# first load dyMono seurat object above, then only run this chunk
dySpher.POSmarkers %>% 
  group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10
DoHeatmap(dySpher, features = top10$gene) + guides(color = "none") +
  theme(text = element_text(size = 25), legend.title = element_text(size=20), 
        legend.text=element_text(size=20))
```

```{r}
# prepare the data for gProfiler (web app) input
dySpher.genes.presto <- wilcoxauc(dySpher, 'seurat_clusters')
nrow(dySpher.genes.presto)
dplyr::count(dySpher.genes.presto, group)
```

```{r}
# filter and order the gene list
dySpher.genes.presto.clust0 <- dySpher.genes.presto %>% 
  dplyr::filter(group == "0" & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(dySpher.genes.presto.clust0) # 24 genes only! Worth running gProfiler on this gene list?
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(dySpher.genes.presto.clust0, 
          "./outputs50K/DAOY_SPHER/daoySpheroid.RiboRetained.cluster0.genes.presto.gProfilerInput.csv", quote = F)
```

```{r}
# filter and order the gene list
dySpher.genes.presto.clust1 <- dySpher.genes.presto %>% 
  dplyr::filter(group == "1" & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(dySpher.genes.presto.clust1) # 134 genes only!
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(dySpher.genes.presto.clust1, 
          "./outputs50K/DAOY_SPHER/daoySpheroid.RiboRetained.cluster1.genes.presto.gProfilerInput.csv", quote = F)
```

```{r}
# filter and order the gene list
dySpher.genes.presto.clust2 <- dySpher.genes.presto %>% 
  dplyr::filter(group == "2" & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(dySpher.genes.presto.clust2) # 83 genes only
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(dySpher.genes.presto.clust2, 
          "./outputs50K/DAOY_SPHER/daoySpheroid.RiboRetained.cluster2.genes.presto.gProfilerInput.csv", quote = F)
```


```{r}
# filter and order the gene list
dySpher.genes.presto.clust3 <- dySpher.genes.presto %>% 
  dplyr::filter(group == "3" & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(dySpher.genes.presto.clust3) # 138 genes only
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(dySpher.genes.presto.clust3, 
          "./outputs50K/DAOY_SPHER/daoySpheroid.RiboRetained.cluster3.genes.presto.gProfilerInput.csv", quote = F)
```


```{r}
# filter and order the gene list
dySpher.genes.presto.clust4 <- dySpher.genes.presto %>% 
  dplyr::filter(group == "4" & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(dySpher.genes.presto.clust4) # 296 genes
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(dySpher.genes.presto.clust4, 
          "./outputs50K/DAOY_SPHER/daoySpheroid.RiboRetained.cluster4.genes.presto.gProfilerInput.csv", quote = F)
```



***Clustree***
```{r}
# attempt to use Clustree package to find the right number of clusters
# -----------------------------------------------------------------------------------------------

# Select a range of resolutions
resolution.range <- seq(from = 0, to = 1.6, by = 0.2)

# Find clusters using a range of resolutions, the clustering information is in the metadata slot
dySpher.clusters <- FindClusters(object = dySpher, 
                                      resolution = resolution.range,
                                      verbose = FALSE)
```

```{r ClustreeCBO, fig.height=6}
# the clustering tree finds too many clusters! These clusters are not biologically
# meaningful. See Endnote 'CARP Lab Notebook' > 'Log of Data Analysis' for details

clustree(dySpher.clusters)
```








