---
title: "ONS76-2D_Seurat_EXPLORE1_50K"
author: "JJ"
date: "18/01/2023"
output: html_document
---

```{r graphical_output}
options(bitmapType='cairo-png') # this line of code needed BEFORE knitr code in chunk below
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = TRUE,   # prints the code (if FALSE then only code output is shown)
                      cache = TRUE,
                      fig.path = "./outputs50K/ONS76_2D/figures/")
```

```{r libraries}
suppressPackageStartupMessages({
library(Seurat)
library(glmGamPoi)
library(presto)
library(clustree)
library(tidyverse)
library(magrittr)
library(patchwork)
})
```


```{r}
# load the data from scratch
# load the ONS76-2D raw data (from "working_data" folder)
data_dir <- "./working_data/ONS76-2D/"   # the dot is current dir and is essential!
list.files(data_dir) # should show matrix.mtx.gz, features.tsv.gz, barcodes.tsv.gz
```

```{r}
# note these are .gz files which can be directly read. n = 648 cells (o76mono.data)
o76mono.data <- ReadMtx(mtx = paste0(data_dir, "matrix.mtx.gz"),
                         features = paste0(data_dir, "features.tsv.gz"), 
                         cells = paste0(data_dir, "barcodes.tsv.gz"))
# create the seurat object, keep genes expressed in 10 or more cells
o76mono <- CreateSeuratObject(counts = o76mono.data,
                          min.cells = 10, min.genes=200,
                          project = "ons76mono")

dim(o76mono) # 15,699 genes and 648 cells
```

```{r}
# identify mitochondrial genes
mito.genes <- grep(pattern = "^MT", x = rownames(x = o76mono), value = TRUE)
percent.mito <- 
  Matrix::colSums(o76mono[mito.genes, ])/Matrix::colSums(o76mono)

# add the mitochondrial gene percent to the metadata
o76mono <- 
  AddMetaData(object = o76mono, metadata = percent.mito, col.name = "percent.mito")

# remove mitochondrial genes 
o76mono <- o76mono[ ! grepl("^MT-", rownames(o76mono)), ]

dim(o76mono) # 15,686 genes and 648 cells
```

```{r}
# remove all cells with percent.mito > 10%
o76mono <- subset(o76mono, subset = percent.mito < 0.1)
dim(o76mono) # reduced to 15,686 genes and 474 cells
```

```{r}
# save the NON-normalised, NON-clustered cbo seurat object
saveRDS(o76mono, file = "./outputs50K/ONS76_2D/filt.MitoCellsGenes.RiboRetained.seurat.ons76monolayer.rds")
```

```{r}
o76mono <- readRDS("outputs50K/ONS76_2D/filt.MitoCellsGenes.RiboRetained.seurat.ons76monolayer.rds")
```

```{r}
# load cell cycle genes, calculate cell-cycle difference in advance of regressing out CC difference

# normalise object before running cell cycle scores as per Seurat github issue: https://github.com/satijalab/seurat/issues/1679
o76mono <- NormalizeData(o76mono)

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
# calculate CC difference
o76mono <- CellCycleScoring(o76mono,
                g2m.features = g2m.genes,
                s.features = s.genes)
o76mono$CC.difference <- o76mono$S.Score - o76mono$G2M.Score
```

```{r}
# this object is input for integration - already SCTransformed, CCdiff regressed, and RunPCA()
o76mono.input.integration <- SCTransform(o76mono, 
                   vars.to.regress = "CC.difference",
                   method = "glmGamPoi",
                   vst.flavor = "v2",
                   verbose = FALSE) %>% 
  RunPCA(npcs = 30, verbose = FALSE)
```

```{r}
# save the SCTransformed object, CC difference regressed, PCA reduction, as input for integrated workflow
saveRDS(o76mono.input.integration, "./outputs50K/ONS76_2D/ONS76mono.inputIntegration.RiboRetained.SCTransformed.CCdiffRegressed.PCA.unclustered.rds")
```

```{r}
o76mono <- SCTransform(o76mono, vars.to.regress = "CC.difference", method = "glmGamPoi", verbose = FALSE) %>% 
  RunPCA(verbose = FALSE) %>% 
  RunUMAP(dims=1:30, verbose=FALSE) %>% 
  FindNeighbors(dims=1:30, verbose=FALSE) %>% 
  FindClusters(verbose=FALSE, resolution = 0.5)
```

```{r}
# save the clustered, SCTransformed object above
saveRDS(o76mono, file = "./outputs50K/ONS76_2D/ons76mono.RiboRetained.MitoCellsGenesFilt.SCT.clustered.CCdiffRegressed.rds")
```

```{r}
# load the above object. This object not yet been annotated.
o76mono <- readRDS("outputs50K/ONS76_2D/ons76mono.RiboRetained.MitoCellsGenesFilt.SCT.clustered.CCdiffRegressed.rds")
# if plotting markers using this object scale (ScaleData function) before plotting genes of interest
```

```{r DimplotONS76monoUmapSCTransform, fig.height=6, fig.width=10}
DimPlot(o76mono, label = TRUE)
```

```{r}
# get the markers of each cluster
o76mono.POSmarkers <- FindAllMarkers(object = o76mono, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```

```{r}
# ribosome gene enrichment in cluster 0 when grouping by cluster only and leaving out '..arrange..'
o76mono.POSmarkers %>% 
  dplyr::group_by(cluster) %>%
  dplyr::arrange(desc(avg_log2FC)) %>% 
  slice_head(n = 30)
```

```{r}
# CNTN1 and MEIS1 are expressed of these five
o76mono.POSmarkers %>%
  filter(gene %in% c("NEUROD1", "CNTN1", "CNTN2", "MEIS1", "DCX1"))
```

```{r}
# save the positive markers of ONS76-2D
saveRDS(o76mono.POSmarkers, 
        file = "./outputs50K/ONS76_2D/POS.markers.ons76monolayer.RiboRetained.SCT.clustered.rds")
```

```{r}
o76mono.POSmarkers <- readRDS("outputs50K/ONS76_2D/POS.markers.ons76monolayer.RiboRetained.SCT.clustered.rds")
```


```{r}
# this step is important to avoid a warning re omission of specific genes of interest in the top 20 list of markers from the scale data slot: https://github.com/satijalab/seurat/issues/1369
o76mono <- ScaleData(object = o76mono, features = rownames(o76mono)) 
```

```{r HeatmapONS76MonoTop20markers2clustersRes0.5, fig.height=6, fig.width=10}
o76mono.POSmarkers %>% 
  group_by(cluster) %>%
    top_n(n = 20, wt = avg_log2FC) -> top20
DoHeatmap(o76mono, features = top20$gene) + guides(color = "none") +
  theme(text = element_text(size = 25), legend.title = element_text(size=20), 
        legend.text=element_text(size=20)) 
```

Run presto, then gProfiler on this sample to get an idea of what pathways are active in the different cell clusters.

```{r}
# prepare the data for gProfiler (web app) input
o76mono.genes.presto <- wilcoxauc(o76mono, 'seurat_clusters')
nrow(o76mono.genes.presto)
dplyr::count(o76mono.genes.presto, group)
```

```{r}
head(o76mono.genes.presto, 3)
```

```{r}
# filter and order the gene list
o76mono.genes.presto.clust0 <- o76mono.genes.presto %>% 
  dplyr::filter(group == "0" & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(o76mono.genes.presto.clust0) # 34 genes only
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(o76mono.genes.presto.clust0, 
          "./outputs50K/ONS76_2D/ONS76mono.cluster0.genes.presto.gProfilerInput.csv", quote = F)
```

```{r}
# filter and order the gene list
o76mono.genes.presto.clust1 <- o76mono.genes.presto %>% 
  dplyr::filter(group == "1" & !(feature == "MALAT1") & logFC > 0.25) %>%
  dplyr::arrange(desc(auc)) %>% 
  dplyr::select(feature, auc)

nrow(o76mono.genes.presto.clust1) # 428 genes
```

```{r}
# gProfiler input - use Filezilla to pull the file to my Mac and then copy and paste the ordered list
# of genes into gProfiler web app
write.csv(o76mono.genes.presto.clust1, 
          "./outputs50K/ONS76_2D/ONS76mono.cluster1.genes.presto.gProfilerInput.csv", quote = F)
```


***Clustree***
```{r}
# attempt to use Clustree package to find the right number of clusters
# -----------------------------------------------------------------------------------------------

# Select a range of resolutions
resolution.range <- seq(from = 0, to = 1.8, by = 0.2)

# Find clusters using a range of resolutions, the clustering information is in the metadata slot
ons76.2d.clusters <- FindClusters(object = o76mono, 
                                      resolution = resolution.range,
                                      verbose = FALSE)
```

```{r ClustreeCBO, fig.height=6}
# the clustering tree finds too many clusters! These clusters are not biologically
# meaningful as pct.1 and pct.2 are so similar.
# with res = 0.8 there are 4 clusters; with res = 1 there are 5 clusters.
# use marker differences (FindAllMarkers) and pathway enrichment to tell how many clusters have distinct enrichments. 

clustree(ons76.2d.clusters)
```

Find the genes differentially expressed in G1 phase vs other (G2M and S phase) cells

```{r}
head(o76mono@meta.data)
```

```{r}
Idents(o76mono) <- "Phase"
```

```{r}
g1.o76mono.markers <- FindAllMarkers(object = o76mono, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```

```{r}
nrow(g1.o76mono.markers) # 986 genes differentially expressed between G1, G2M and S phases
```

```{r}
g1.o76mono.markers %>% 
dplyr::filter(cluster == "G1") %>% 
  head(3)
```


```{r}
# extract the G1 only cells from o76mono (this 'o76mono' object is the already CLUSTERED object)
o76mono.g1.cellIDs <- WhichCells(o76mono, idents = "G1")
length(o76mono.g1.cellIDs)
```

```{r}
# these cell IDs look correctly formatted
# object o76mono has to be "filt.RiboMitoCellsGenes.seurat.ons76monolayer.rds" above!
o76mono.g1cells <- subset(o76mono, cells = o76mono.g1.cellIDs)
head(WhichCells(o76mono.g1cells))
```

```{r}
dim(o76mono.g1cells) # 148 cells in G1 phase
```

```{r}
# create an object suitable for integration (don't need to regress cell cycle!)
# object o76mono has to be "filt.RiboMitoCellsGenes.seurat.ons76monolayer.rds" above!
o76mono.g1cells.input.integration <- SCTransform(o76mono.g1cells,
                                                  method = "glmGamPoi",
                                                  vst.flavor = "v2",
                                                  verbose = FALSE) %>% 
  RunPCA(npcs = 30, verbose = FALSE)
```

```{r}
dim(o76mono.g1cells.input.integration) # there are 148 cells, which is correct
```

```{r}
# save the "o76mono.g1cells.input.integration" object
saveRDS(o76mono.g1cells.input.integration, 
        file = "./outputs50K/ONS76_2D/G1phaseCells.ONS76monolayer.inputIntegration.RiboRetained.SCTransformed.PCA.unclustered.rds")
```















