---
title: "ONS76-CBO_Seurat_EXPLORE1_50K"
author: "JJ"
date: "11/08/2022"
output: html_document
---

```{r graphical_output}
options(bitmapType='cairo-png') # this line of code needed BEFORE knitr code in chunk below
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = TRUE,   # prints the code (if FALSE then only code output is shown)
                      cache = TRUE)
```

```{r libraries}
library(Seurat)
library(glmGamPoi)
library(Matrix)
library(patchwork)
library(tidyverse)
```

```{r load_filteredSeuratObject}
# load full filtered (genes and cells) seurat object

filt.cboONS76.seurat <- readRDS("outputs50K/ONS76-CBO/filtCellsGenes.ons76cbo.seurat.rds")
```

```{r Plot1_SCTransform_UMAPclustering}
# Perform SCTransform
# Perform dimensionality reduction by PCA and UMAP embedding
# FindClusters is run with only the default resolution parameter (= 0.8)
# 10 clusters identified

filt.cboONS76.seurat <- SCTransform(filt.cboONS76.seurat, method = "glmGamPoi", verbose = FALSE)

filt.cboONS76.seurat <- RunPCA(filt.cboONS76.seurat, verbose = FALSE)

filt.cboONS76.seurat <- RunUMAP(filt.cboONS76.seurat, dims = 1:30, verbose = FALSE)

filt.cboONS76.seurat <- FindNeighbors(filt.cboONS76.seurat, dims = 1:30, verbose = FALSE)

filt.cboONS76.clusters.seurat <- FindClusters(filt.cboONS76.seurat, verbose = FALSE)

DimPlot(filt.cboONS76.clusters.seurat, label = TRUE) # '+ NoLegend()' is an option to insert here
```

```
# saved the SCTransformed, clustered 'filt.cbo.clusters.seurat' Seurat object 
# to the folder 'outputs50K'. Running DimPlot() command on this object should generate the same
# UMAP projection every time

saveRDS(filt.cboONS76.clusters.seurat, file = "./outputs50K/ONS76-CBO/filt.cboONS76.clusters.seurat.rds")
```
```{r load_clustered_SeuratObject}
filt.cboONS76.clusters <- readRDS("outputs50K/ONS76-CBO/filt.cboONS76.clusters.seurat.rds")
```

```
# saved the last seurat object, 'filt.cboONS76.seurat'

saveRDS(filt.cboONS76.seurat, file = "./outputs50K/ONS76-CBO/filt.cboONS76.seurat.rds")
```
```{r load_last_filt.cboONS76.seurat_object}
filt.cboONS76 <- readRDS("outputs50K/ONS76-CBO/filt.cboONS76.seurat.rds")
```


```{r ElbowPlot_ndims=50}
# elbow plot shows that there is an elbow at PC ~10, but the graph does not level off after
# PC 15 showing there is some additional information to ~ PC 40.
# The input object is the CLUSTERED saved seurat object, and this gives the same result as
# the seurat object generated by the FindNeighbours() command.

ElbowPlot(filt.cboONS76.clusters, ndims = 50, reduction = "pca")
```

```{r differential_genes_by_cluster_cboONS76_SCT}
# Find positive markers for each of the 11 clusters
cboONS76.cluster.markers <- FindAllMarkers(filt.cboONS76.clusters, min.pct = 0.25, only.pos = TRUE)
```

```{r cell_counts_perCluster}
# there are 2545 cells in total (BEFORE any ribosome filtering), which is correct, and the cell numbers 
# per cluster are shown below.

cell.num <- table(filt.cboONS76.clusters@active.ident)
cell.num
sum(cell.num)
```

```
# save cbo.cluster.markers as a csv file

write.csv(cboONS76.cluster.markers, "./outputs50K/ONS76-CBO/cboONS76.cluster.markers.csv", quote = F)
```

```{r load_cbo.cluster.markers}
cboONS76.cluster.markers <- read.csv("outputs50K/ONS76-CBO/cboONS76.cluster.markers.csv", 
                                    header = TRUE, 
                                    stringsAsFactors = FALSE)
```

```{r cluster0_cbo.cluster.markers_top10markers}
# cluster 0 = roof plate/choroid plexus
cluster0.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 0, ] %>%
  head(n=20)

cluster0.markers
```

```{r cluster1_cbo.cluster.markers_top10markers}
# cluster 1 = probable glia
cluster1.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 1, ] %>%
  head(n=20)

cluster1.markers
```

```{r cluster2_cbo.cluster.markers_top10markers}
# cluster 2 = 4th ventricle derivatives/choroid plexus
cluster2.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 2, ] %>%
  head(n=20)

cluster2.markers
```

```{r cluster3_cbo.cluster.markers_top10markers}
# cluster 3 = GCP/granule neuron
cluster3.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 3, ] %>%
  head(n=20)

cluster3.markers
```

```{r cluster4_cbo.cluster.markers_top10markers}
# cluster 4 = rhombic lip/GCP lineage
cluster4.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 4, ] %>%
  head(n=20)

cluster4.markers
```

```{r cluster5_cbo.cluster.markers_top10markers}
# cluster 5 = ?ONS76 cells
cluster5.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 5, ] %>%
  head(n=20)

cluster5.markers
```

```{r cluster6_cbo.cluster.markers_top10markers}
# cluster 6 = could be inhibitory GABAergic cerebellar nuclei/interneurons/PN
cluster6.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 6, ] %>%
  head(n=20)

cluster6.markers
```

```{r cluster7_cbo.cluster.markers_top10markers}
# cluster 7 = GCP/granule neuron
cluster7.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 7, ] %>%
  head(n=20)

cluster7.markers
```

```{r cluster8_cbo.cluster.markers_top10markers}
# cluster 8 = ?glia (but could these be ONS76 cells??)
cluster8.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 8, ] %>%
  head(n=20)

cluster8.markers
```

```{r cluster9_cbo.cluster.markers_top10markers}
# cluster 9 =  most likely glia 
cluster9.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 9, ] %>%
  head(n=20)

cluster9.markers
```

```{r cluster10_cbo.cluster.markers_top10markers}
# cluster 10 = ONS76 cells
cluster10.markers <- cboONS76.cluster.markers[cboONS76.cluster.markers$cluster == 10, ] %>%
  head(n=20)

cluster10.markers
```

```{r}
# cluster 5 contained many ribosomal genes, so TRY FILTERING ON RIBOSOMAL GENE PERCENTAGE
#----------------------------------------------------------------------------------------

# use the full filtered (for cells and genes and mitoch percent) seurat object
```

```{r load_filteredSeuratObject}
# load full filtered (genes and cells) seurat object

filt.cboONS76.seurat <- readRDS("outputs50K/ONS76-CBO/filtCellsGenes.ons76cbo.seurat.rds")
```

```{r calc_ribosomal_percent}
# calculate ribosomal percentage

filt.cboONS76.seurat[["percent.ribo"]] <- PercentageFeatureSet(filt.cboONS76.seurat, pattern = "^RP[SL]")
```

```{r}
summary(filt.cboONS76.seurat@meta.data$percent.ribo)
```

```{r}
VlnPlot(filt.cboONS76.seurat, features = c("percent.mt", "percent.ribo"), ncol = 3)
```

```{r}
# In https://kb.10xgenomics.com/hc/en-us/articles/218169723-What-fraction-of-reads-map-to-ribosomal-proteins- on the 10X Genomics scRNA-seq website there is a table of percent ribosomal genes in different cell types. For neurons the upper limit is 20%. So try filtering 'filt.cboONS76.seurat' for ribosomal genes and repeat the clustering.

# View metadata data frame, stored in object@meta.data
metadata <- filt.cboONS76.seurat[[]]

# number of cells with percent.ribo > 20%: 1229 cells
# number of cells with percent.ribo < 20%: 1316 cells

nrow(metadata[metadata$percent.ribo > 20, ])

nrow(metadata[metadata$percent.ribo < 20, ])
```

```{r filter_on_percent.ribo<20}
# this object, as expected, has 1316 cells, in which all cells have percent.ribo < 20%

full.ribo.filt.cboONS76 <- subset(filt.cboONS76.seurat, subset = percent.ribo < 20)
dim(full.ribo.filt.cboONS76)
```

```{r Plot_SCTransform_UMAP_clustering}
# Perform SCTransform
# Perform dimensionality reduction by PCA and UMAP embedding
# FindClusters is run with only the default resolution parameter (= 0.8)
# 10 clusters identified

full.ribo.filt.cboONS76 <- SCTransform(full.ribo.filt.cboONS76, method = "glmGamPoi", verbose = FALSE)

full.ribo.filt.cboONS76 <- RunPCA(full.ribo.filt.cboONS76, verbose = FALSE)

full.ribo.filt.cboONS76 <- RunUMAP(full.ribo.filt.cboONS76, dims = 1:30, verbose = FALSE)

full.ribo.filt.cboONS76 <- FindNeighbors(full.ribo.filt.cboONS76, dims = 1:30, verbose = FALSE)

full.ribo.filt.clust.cboONS76 <- FindClusters(full.ribo.filt.cboONS76, verbose = FALSE)

# 11 clusters are now detected
DimPlot(full.ribo.filt.clust.cboONS76, label = TRUE) # '+ NoLegend()' is an option to insert here
```

```
# saved the last seurat object, 'full.ribo.filt.cboONS76'

saveRDS(full.ribo.filt.cboONS76, file = "./outputs50K/ONS76-CBO/full.ribo.filt.cboONS76.rds")
```

```
# saved the CLUSTERED 'full.ribo.filt.clust.cboONS76' Seurat object to the folder 'outputs50K'

saveRDS(full.ribo.filt.clust.cboONS76, file = "./outputs50K/ONS76-CBO/full.ribo.filt.clust.cboONS76.rds")
```


```{r cell_counts_perCluster_ribo_filtered}
# there are 1316 cells in total, which is correct, and the cell numbers per cluster are shown below.

cell.num.riboFilt <- table(full.ribo.filt.clust.cboONS76@active.ident)
cell.num.riboFilt
sum(cell.num.riboFilt)
```

## save the ribosome expression filtered seurat objects (incl. clustered object)

```{r differential_genes_by_cluster_cboONS76_ribo<20%}
# Find positive markers for each of the 9 clusters
cboONS76.cluster.markers.ribo20 <- FindAllMarkers(full.ribo.filt.clust.cboONS76, min.pct = 0.25, only.pos = TRUE)
```

```
# save cboONS76.cluster.markers.ribo20 as a csv file. This object has percent.ribo < 20

write.csv(cboONS76.cluster.markers.ribo20, "./outputs50K/ONS76-CBO/cboONS76.cluster.markers.ribo20.csv", quote = F)
```

```{r load_clusterMarkersCSV_ribo<20}
cboONS76.cluster.markers.ribo20 <- read.csv("outputs50K/ONS76-CBO/cboONS76.cluster.markers.ribo20.csv", 
                                       header = TRUE, 
                                       stringsAsFactors = FALSE)
```

```{r cluster0_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 0 = probable roof plate/choroid plexus
cluster0.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 0, ] %>%
  head(n=20)

cluster0.markers.ribo20
```

```{r cluster1_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 1 = GCP/RL lineage (incl UBC)/granule neuron

cluster1.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 1, ] %>%
  head(n=20)

cluster1.markers.ribo20
```

```{r cluster2_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 2 = RL/GCP/granule neuron

cluster2.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 2, ] %>%
  head(n=20)

cluster2.markers.ribo20
```

```{r cluster3_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 3 = inhibitory GABAergic cerebellar nuclei/interneurons/PN

cluster3.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 3, ] %>%
  head(n=20)

cluster3.markers.ribo20
```

```{r cluster4_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 4 = probable glia

cluster4.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 4, ] %>%
  head(n=20)

cluster4.markers.ribo20
```

```{r cluster5_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 5 = probable glia

cluster5.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 5, ] %>%
  head(n=20)

cluster5.markers.ribo20
```

```{r cluster6_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 6 = undetermined (??ONS76 cells)

cluster6.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 6, ] %>%
  head(n=20)

cluster6.markers.ribo20
```

```{r cluster7_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 7 = rhombic lip/proliferative granule cells/GCP. ?related to ONS76 cells

cluster7.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 7, ] %>%
  head(n=20)

cluster7.markers.ribo20
```

```{r cluster8_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 8 = ?ONS76 cells which are in RL lineage.

cluster8.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 8, ] %>%
  head(n=20)

cluster8.markers.ribo20
```

```{r cluster9_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 9 = glia

cluster9.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 9, ] %>%
  head(n=20)

cluster9.markers.ribo20
```

```{r cluster10_cboONS76.cluster.markers.ribo20_top10markers}
# cluster 10 = RL/GCP lineage

cluster10.markers.ribo20 <- cboONS76.cluster.markers.ribo20[cboONS76.cluster.markers.ribo20$cluster == 10, ] %>%
  head(n=20)

cluster10.markers.ribo20
```

```{r remove_ribo_genes}
# FILTER OUT ALL RIBOSOMAL GENES, THEN ALL MITOCHONDRIAL GENES (ON THE CELLS WHICH HAVE ALREADY BEEN REMOVED
# THAT HAVE PERCENT.MITO < 10% BEFORE DOING THE CLUSTERING), DON'T REMOVE ANY MORE ACTUAL CELLS
#-------------------------------------------------------------------------------------

# remove ribosomal genes first
filt.noRibo.ons76cbo <- filt.cboONS76.seurat[ ! grepl('^RP[SL]', rownames(filt.cboONS76.seurat)), ]
```

```{r check_ribo_removed}
# this has worked - 97 ribosomal genes have been removed from the new Seurat object
dim(filt.cboONS76.seurat)
dim(filt.noRibo.ons76cbo)
```

```{r remove_mitoch_genes}
# remove mitochondrial genes 
filt.noRiboMito.ons76cbo <- filt.noRibo.ons76cbo[ ! grepl("^MT-", rownames(filt.noRibo.ons76cbo)), ]
```

```{r check_filtering}
# check if ribosome and mitochondrial gene filtering works - it does!
dim(filt.noRibo.ons76cbo)
dim(filt.noRiboMito.ons76cbo)
```

```
# save the ribosome gene-filtered and mitochondrial gene-filtered seurat object.

saveRDS(filt.noRiboMito.ons76cbo, file = "./outputs50K/ONS76-CBO/filt.NoRiboNoMito.cboONS76.rds")
```

```{r load_ons76cbo_NoRiboNoMito}
filt.noRiboMito.ons76cbo <- readRDS("outputs50K/ONS76-CBO/filt.NoRiboNoMito.cboONS76.rds")
```

```{r DimPlot_SCTransform_UMAPclustering}
# Perform SCTransform
# Perform dimensionality reduction by PCA and UMAP embedding
# FindClusters is run with only the default resolution parameter (= 0.8)
# XX clusters identified

filt.noRiboMito.ons76cbo <- SCTransform(filt.noRiboMito.ons76cbo, method = "glmGamPoi", verbose = FALSE)

filt.noRiboMito.ons76cbo <- RunPCA(filt.noRiboMito.ons76cbo, verbose = FALSE)

filt.noRiboMito.ons76cbo <- RunUMAP(filt.noRiboMito.ons76cbo, dims = 1:30, verbose = FALSE)

filt.noRiboMito.ons76cbo <- FindNeighbors(filt.noRiboMito.ons76cbo, dims = 1:30, verbose = FALSE)

filt.noRiboMito.ons76cbo.clusters <- FindClusters(filt.noRiboMito.ons76cbo, verbose = FALSE)

DimPlot(filt.noRiboMito.ons76cbo.clusters, label = TRUE) # '+ NoLegend()' is an option to insert here
```

```
# SAVE THE 'filt.noRiboMito.ons76cbo.clusters' seurat object

saveRDS(filt.noRiboMito.ons76cbo.clusters, file = "./outputs50K/ONS76-CBO/filt.noRiboMito.ons76cbo.clusters.rds")
```

```{r load_filt.noRiboMito.ons76cbo.clusters.rds}
# load the saved clustered seurat object with ribosome and mitoch genes removed

filt.noRiboMito.ons76cbo.clusters <- readRDS("outputs50K/ONS76-CBO/filt.noRiboMito.ons76cbo.clusters.rds")
```

```{r differential_genes_by_cluster_filt.noRiboMito.ons76cbo.clusters}
# Find positive markers for each of the 11 clusters of 'filt.noRiboMito.cbo.clusters'

ons76cbo.cluster.markers.noRiboMito <- FindAllMarkers(filt.noRiboMito.ons76cbo.clusters, min.pct = 0.25, only.pos = TRUE)
```

```{r cell_counts_perCluster}
# there are 2545 cells in total, which is correct, and the cell numbers per cluster are shown below.

cell.num.riboFilt <- table(filt.noRiboMito.ons76cbo.clusters@active.ident)
cell.num.riboFilt
sum(cell.num.riboFilt)
```

```{r}
# save 'ons76cbo.cluster.markers.noRiboMito' as a csv file. This object has NO mitochondrial 
# or ribosomal genes.
# The object has already been filtered to keep cells with mitoch gene expression < 10%.

write.csv(ons76cbo.cluster.markers.noRiboMito,
          "./outputs50K/ONS76-CBO/ons76cbo.cluster.markers.noRiboMito.csv", 
          quote = F)
```

```{r load_ons76cbo.cluster.markers.noRiboMito.csv}
ons76cbo.cluster.markers.noRiboMito <- read.csv(
                                      "outputs50K/ONS76-CBO/ons76cbo.cluster.markers.noRiboMito.csv", 
                                       header = TRUE, 
                                       stringsAsFactors = FALSE)
```

```{r cluster0_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 0 manual = roof plate/CP 

cluster0.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 0, ] %>%
  head(n=10)

cluster0.markers
```

```{r cluster1_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 1 manual = possible glia??
cluster1.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 1, ] %>%
  head(n=10)

cluster1.markers
```

```{r cluster2_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 2 manual = GCP/granule but could be ONS76

cluster2.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 2, ] %>%
  head(n=20)

cluster2.markers
```

```{r cluster3_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 3 manual = CP/4th ventricle

cluster3.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 3, ] %>%
  head(n=10)

cluster3.markers
```

```{r cluster4_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 4 manual = possible glia
cluster4.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 4, ] %>%
  head(n=10)

cluster4.markers
```

```{r cluster5_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 5 manual = possible inhibitory GABAergic cerebellar nuclei/interneurons/PN

cluster5.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 5, ] %>%
  head(n=10)

cluster5.markers
```

```{r cluster6_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 6 manual = GCP/granule neuron - a bit more similar to cluster 6 of CBO sample

cluster6.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 6, ] %>%
  head(n=20)

cluster6.markers
```

```{r cluster7_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 7 manual = glial cells

cluster7.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 7, ] %>%
  head(n=10)

cluster7.markers
```

```{r cluster8_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 8 manual = rhombic lip, GCP, proliferative granule cells

cluster8.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 8, ] %>%
  head(n=10)

cluster8.markers
```

```{r cluster9_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 9 manual = uncertain
cluster9.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 9, ] %>%
  head(n=10)

cluster9.markers
```

```{r cluster10_ons76cbo.cluster.markers.noRiboMito_top10markers}
# cluster 10 manual = ONS76 cells?
cluster10.markers <- ons76cbo.cluster.markers.noRiboMito[ons76cbo.cluster.markers.noRiboMito$cluster == 10, ] %>%
  head(n=20)

cluster10.markers
```

```{r Dotplot_all_seppMarkers+cilia, fig.height=10}
# from the Sepp paper repeat Dotplot with TF and some key non-TF markers
# added markers of ciliated cells from cluster10 above.
# used the argument col.min = 0 so that average expression scale is from 0 to 2.5 in key

sepp.all.markers <- c("TFAP2A", "PAX3", "RFX4", "TCFL71", "TCF7L2", "GLIS3", "SOX6", "HOPX", "TSC22D4",  
                      "ID4", "NCKAP5", "SLIT2", "CLYBL", "SLC1A3", "SLC6A11", "AQP4",  #astroglial/progenitor
                      
                      "ESRRB", "FOXP1", "FOXP2", "FOXP4", "MEF2C", "RORB", "CDH9", "ETV1", "EBF1", "EBF2", 
                      "SKOR2", "DAB1", "IPTR",   # Purkinje
                      
                      "NOTCH1",    # VZ neuroblast
             
                      "PAX2", "NFIA", "NFIB", "TFAP2B", "BHLHE22", "PRDM8",  # interneuron
                      
                      "ZFHX3", "ZFHX4",   # GABAergic deep nuclei neurons
             
                      "TOP2A", "ATOH1", "LMX1A", "OTX2","ETV6", "PAX6", "BARHL1", "E2F3", "ST18", "SATB2", 
                      "ZBTB18", "NEUROD1", "ZIC1", "ZIC4", "GABAR6", "CNTN1", "CNTN2", "KLF9", "NR3C1", "LMO3", 
                      "SYNPR", "KCNIP4", "HCRTR2", 
                      "EOMES", "TRPC3", "GRM1")
                      # UBC/GCP/granule/glut deep cerebellar nuclei                                                                   
seppAll.cilia.stem.markers <- c(sepp.all.markers, "CCNO", "CFAP299", "ROPN1L", "C11orf88", "ANKRD66", "C20orf85", 
                                "STOML3", "TEKT4", "SNTN", "MEIS1", "POU3F2", "HOXB2", "MEIS2", "GRIA4")

DotPlot(object = filt.noRiboMito.ons76cbo.clusters, features = seppAll.cilia.stem.markers, col.min = 0) +
  coord_flip()
```

```{r granule_lineage_by_cluster, fig.height=10}
# plot of the clusters containing granule/RL lineage - clusters 2, 4, 6, 9 and 10 contain RL/granule
# lineage.
# CDH1 is expressed (in WT cells and ONS76 cells), but CDH5 (marker of ONS76 cells) is not expressed.
# CD44 is not expressed or expressed very little.
# ITGB1 is also not good at discriminating WT CBO from ONS76-CBO samples

VlnPlot(filt.noRiboMito.ons76cbo.clusters, features = c("PAX6", "NEUROD1", "CNTN1", "CNTN2", "MEIS1", "GRIA4", "POU3F2"))
```

```{r cntn2_cluster2,10}
# CHECK ABOVE CANDIDATE GENES WHICH ARE UPREGULATED IN ONS76 CELLS VS WT CELLS IN CO-CULTURE
#----------------------------------------------------------------------------------------------------
# CLUSTER 2, MEIS1 expression in cells: pct.1 = 28%, pct.2 (all other cells) = 7%, avg_log2FC = 0.429;
# adj p-val = 1.871e-27

# CLUSTER 10, CNTN2 expression in cells: pct.1 = 44%, pct.2 = 9%, avg_log2FC = 1.150;
# adj p-val = 1.736e-20

cntn2.clusters.2.10 <- ons76cbo.cluster.markers.noRiboMito[((ons76cbo.cluster.markers.noRiboMito$cluster == 2 | ons76cbo.cluster.markers.noRiboMito$cluster == 10) & ons76cbo.cluster.markers.noRiboMito$gene == "CNTN2"), ]

cntn2.clusters.2.10
```

```{r meis1_cluster10}
# CLUSTER 10, MEIS1 expression in cells: pct.1 = 70%, pct.2 = 2%, avg_log2FC = 1.783;
# adj p-val = 2.349e-195

meis1.cluster.10 <- ons76cbo.cluster.markers.noRiboMito[(ons76cbo.cluster.markers.noRiboMito$cluster == 10 & ons76cbo.cluster.markers.noRiboMito$gene == "MEIS1"), ]

meis1.cluster.10
```

```{r gria4_cluster10}
# CLUSTER 10, GRIA4 expression in cells: pct.1 = 29%, pct.2 = 1%, avg_log2FC = 0.688;
# adj p-val = 1.721e-60

gria4.cluster.10 <- ons76cbo.cluster.markers.noRiboMito[(ons76cbo.cluster.markers.noRiboMito$cluster == 10 & ons76cbo.cluster.markers.noRiboMito$gene == "GRIA4"), ]

gria4.cluster.10
```

```{r pou3f2_cluster10}
# CLUSTER 10, POU3F2 expression in cells: pct.1 = 50%, pct.2 = 0.9%, avg_log2FC = 0.997;
# adj p-val = 7.905e-169

pou3f2.cluster.10 <- ons76cbo.cluster.markers.noRiboMito[(ons76cbo.cluster.markers.noRiboMito$cluster == 10 & ons76cbo.cluster.markers.noRiboMito$gene == "POU3F2"), ]

pou3f2.cluster.10
```









